name: build-unsigned-ipa

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Build archive (no code signing)
        run: |
          mkdir -p out
          xcodebuild \
            -scheme IFMI \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "$(pwd)/out/IFMI.xcarchive" \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_STYLE=Manual \
            archive

      - name: Package unsigned .ipa
        run: |
          APP_PATH="out/IFMI.xcarchive/Products/Applications/IFMI.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "App not found at $APP_PATH"
            exit 1
          fi
          mkdir -p out/Payload
          cp -R "$APP_PATH" out/Payload/
          (cd out && zip -r IFMI-unsigned.ipa Payload)
          ls -lah out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: IFMI-unsigned-ipa
          path: out/IFMI-unsigned.ipa
